from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import io
from datetime import datetime

def generate_investigation_report(wallet_data: dict, fraud_data: dict, explanation_data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    # Custom styles
    title_style = ParagraphStyle('Title', parent=styles['Title'], fontSize=24, textColor=colors.HexColor('#1a1a2e'), spaceAfter=6)
    header_style = ParagraphStyle('Header', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#0f3460'), spaceAfter=4)
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, spaceAfter=4)
    story = []
    # Title
    story.append(Paragraph("CryptoShield AI", title_style))
    story.append(Paragraph("Cryptocurrency Fraud Investigation Report", styles['Heading2']))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0f3460')))
    story.append(Spacer(1, 0.2*inch))
    # Wallet Summary
    story.append(Paragraph("Wallet Summary", header_style))
    wallet_table_data = [
        ["Field", "Value"],
        ["Address", wallet_data.get("address", "N/A")],
        ["Blockchain", wallet_data.get("blockchain", "N/A")],
        ["Category", wallet_data.get("category", "Unknown")],
        ["Transaction Count", str(wallet_data.get("tx_count", 0))],
        ["Balance", f"{wallet_data.get('balance', 0):.6f}"],
        ["Last Active", str(wallet_data.get("last_active", "N/A"))],
    ]
    t = Table(wallet_table_data, colWidths=[2*inch, 4*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f3460')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f4ff')]),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))
    # Fraud Score
    story.append(Paragraph("Fraud Risk Assessment", header_style))
    fraud_score = fraud_data.get("fraud_score", 0)
    risk_level = fraud_data.get("risk_level", "unknown")
    confidence = fraud_data.get("confidence", 0)
    fraud_color = colors.green if fraud_score < 0.3 else colors.orange if fraud_score < 0.6 else colors.red
    risk_table_data = [
        ["Metric", "Value"],
        ["Fraud Score", f"{fraud_score:.1%}"],
        ["Risk Level", risk_level.upper()],
        ["Confidence", f"{confidence:.1%}"],
        ["Connected Wallets", str(fraud_data.get("connected_wallets", 0))],
        ["Cross-Chain Activity", "Yes" if fraud_data.get("cross_chain_activity") else "No"],
        ["Model Version", fraud_data.get("model_version", "N/A")],
    ]
    t2 = Table(risk_table_data, colWidths=[2*inch, 4*inch])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f3460')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f4ff')]),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('TEXTCOLOR', (1, 2), (1, 2), fraud_color),
        ('FONTNAME', (1, 2), (1, 2), 'Helvetica-Bold'),
    ]))
    story.append(t2)
    story.append(Spacer(1, 0.2*inch))
    # Risk Factors
    risk_factors = explanation_data.get("risk_factors", [])
    if risk_factors:
        story.append(Paragraph("Risk Factors Identified", header_style))
        for factor in risk_factors:
            story.append(Paragraph(f"• {factor}", body_style))
        story.append(Spacer(1, 0.1*inch))
    # AI Reasoning
    reasoning = explanation_data.get("reasoning_text", "")
    if reasoning:
        story.append(Paragraph("AI Model Reasoning", header_style))
        story.append(Paragraph(reasoning, body_style))
        story.append(Spacer(1, 0.1*inch))
    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Paragraph("This report was generated by CryptoShield AI. For investigative purposes only.", 
                            ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.grey)))
    doc.build(story)
    buffer.seek(0)
    return buffer.read()
